targets:
  $default:
    builders:
      json_parse_model|json:
        enabled: True
builders:
  json:
    import: "package:json_parse_model/builder.dart"
    builder_factories: 
      - "json2ModelPrintBuilder"
    build_extensions: {"^assets/json/{{}}.json": ["lib/json2model_gen/{{}}.dart"]}
    build_to: source
    auto_apply: root_package
    defaults:
      generate_for: 
        include:
        exclude: