name: json_parse_model
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  code_builder: ^4.9.0
  dart_style: ^2.3.4
  http: ^1.1.2
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
